In [8]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)

training_input = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]
                          ])
training_output = np.array([[0,1,1,0]]).T #this is a row we will transpose it to make a column

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1
print ('Random synaptic weights: ')
print (synaptic_weights)

Random synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [13]:
for iteration in range (200000):
    input_layer = training_input
    output = sigmoid(np.dot(input_layer, synaptic_weights))

    error = training_output - output
    adjustment = error * sigmoid_derivative(output)
    synaptic_weights += np.dot(input_layer.T, adjustment)

print("Synaptic weights after training: ")
print(synaptic_weights)

print("Output after training: ")
print(output)

Synaptic weights after training: 
[[12.71639134]
 [-0.20391855]
 [-6.15452135]]
Output after training: 
[[0.00211936]
 [0.99827008]
 [0.99858875]
 [0.00172908]]
