# Trying to create a Neural Network

In [17]:
import sys
import numpy as np
import matplotlib
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

### Single Neuron
Each input needs a weight associated with it. Inputs are the data that we pass into the model
to get desired outputs, while the weights are the parameters that that change inside the model during the training phase, along with biases that also change during training.

Since we’re modeling a single neuron, we only have one bias, as there’s just one bias value per neuron.

In [4]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

This neuron sums each input multiplied by that input’s weight, then adds the bias. All the neuron
does is take the fractions of inputs, where these fractions (weights) are the adjustable parameters, and adds another adjustable parameter — the bias — then outputs the result.

In [5]:
output = (inputs[0]*weights[0] +
          inputs[1]*weights[1]+
          inputs[2]*weights[2]+ bias)

print(output)

2.3


### Layer of Neurons
Each neuron in a layer takes exactly the same input — the input
given to the layer (which can be either the training data or the output from the previous layer),
but contains its own set of weights and its own bias, producing its own unique output. The layer’s output is a set of each of these outputs — one per each neuron.

In [6]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [
          #Neuron 1
          inputs[0]*weights1[0] +
          inputs[1]*weights1[1]+
          inputs[2]*weights1[2]+ 
          inputs[3]*weights1[3]+ bias1,
          
          #Neuron 2
          inputs[0]*weights2[0] +
          inputs[1]*weights2[1]+
          inputs[2]*weights2[2]+ 
           inputs[3]*weights2[3]+ bias2,
         
          #Neuron 3
          inputs[0]*weights3[0] +
          inputs[1]*weights3[1]+
          inputs[2]*weights3[2]+ 
          inputs[3]*weights3[3]+ bias3]

print(output)

[4.8, 1.21, 2.385]


This is called a fully connected neural network — every neuron in the current layer has connections to every neuron from the previous layer. 

In [7]:
inputs = [1, 2, 3, 2.5]

weights=[ [0.2, 0.8, -0.5, 1],
         [0.5, -0.91, 0.26, -0.5], 
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs=[]

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    

    for n_input, weight in zip (inputs, neuron_weights):
        neuron_output +=n_input*weight
    
    neuron_output += neuron_bias
    
    layer_outputs.append(neuron_output)
    
print (layer_outputs)

[4.8, 1.21, 2.385]


### Single Neuron with NumPy

In [8]:
inputs = [1, 2, 3, 2.5]
weights= [0.2, 0.8, -0.5, 1]
bias = 2

outputs = np.dot(weights, inputs) +bias

print(outputs)

4.8


### A layer of Neurons in NumPy

##### Dot product
`a=[1,2,3]
 b=[2,3,4]
 dot_prod = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
 output: 20`

In [9]:
inputs = [1, 2, 3, 2.5]

weights=[ [0.2, 0.8, -0.5, 1],
         [0.5, -0.91, 0.26, -0.5], 
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)

[4.8   1.21  2.385]


### A Batch Of Data
##### Example

In [10]:
batch = [[1,5,6,2],
         [3,2,1,3],
         [5,2,1,2],
         [6,4,8,4],
         [2,8,5,3],
         [1,1,9,4],
         [6,6,0,4],
         [8,7,6,4]]

shape = [2,4]

### A Layer of Neurons and Batch of Data w/ NumPy

In [11]:
inputs = [[1,2,3,2.5],
          [2,5,-1,2],
          [-1.5,2.7,3.3,-0.8]]

weights=[ [0.2, 0.8, -0.5, 1],
         [0.5, -0.91, 0.26, -0.5], 
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print (layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


### Adding layers

In [12]:
inputs = [[1,2,3,2.5],
          [2,5,-1,2],
          [-1.5,2.7,3.3,-0.8]]

weights=[ [0.2, 0.8, -0.5, 1],
         [0.5, -0.91, 0.26, -0.5], 
         [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1,2,-0.5]

layer_outputs1 = np.dot(inputs, np.array(weights).T) + biases
layer_outputs2 = np.dot(layer_outputs1, np.array(weights2).T) + biases2

print (layer_outputs2)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


### Dense Layer Class/ Fully Connected NN
We will have randon initialization of weights and biases.
The idea here is to start a model with non-zero values small enough that they won't affect training

In [25]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        
        #initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    #forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
            
# create dataset
X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 inputs and 3 outputs
dense1 = Layer_Dense(2, 3)

# Forward pass of training data through this layer
dense1.forward(X)

#output
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-4.3361859e-05 -8.5417814e-05 -9.9373065e-05]
 [-7.3564916e-05  1.4769069e-05 -1.5383620e-04]
 [-1.3284820e-04 -2.3827555e-04 -3.0228650e-04]
 [-1.8147002e-04 -2.5475977e-04 -4.0638755e-04]]


### Activation Function
##### Linear Activation Fynction
y=x
##### Sigmoid Activation Function
y=1/(1+e^-x)

### ReLU Activation Function

In [26]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]

output = []

for i in inputs:
    if i > 0:
        output.append(i)
    else:
        output.append(0)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [27]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)


In [31]:
class Activation_Softmax:
    
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims= True))
        
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        
        self.output = probabilities
        
'''X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)

activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)

activation2 = Activation_Softmax()

dense1.forward(X)

activation1.forward(dense1.output)

dense2.forward(activation1.output)

activation2.forward(dense2.output)

print(activation2.output[:5])'''

[[0.33333334 0.33333334 0.33333334]
 [0.33333337 0.3333333  0.33333334]
 [0.33333337 0.33333328 0.33333334]
 [0.3333336  0.33333308 0.33333334]
 [0.33333364 0.33333302 0.3333333 ]]


### Calculating Network Error with Loss
The loss function, also referred to as the cost function, is the
algorithm that quantifies how wrong a model is. Loss is the measure of this metric. Since loss is the model’s error, we ideally want it to be 0.
##### Categorical Cross-Entropy Loss
Categorical cross-entropy is explicitly used to compare
a “ground-truth” probability (y or “targets”) and some predicted distribution (y-hat or “predictions”), so it makes sense to use cross-entropy here.

In [ ]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
    
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_prep, 1e-7, 1 - 1e-7)
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[
                range(samples),
                y_true
            ]
            